services:
  memcached:
    image: memcached:1.6.37
    container_name: memcached-container
    restart: always
    ports:
      - "11211:11211"
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  node:
    build: .
    container_name: node-app-container
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
      - memcached
    environment:
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mysql-data: